### ISSUE TITLE
Invalid attribute values passed to `parse5`

### ISSUE THREAD

**Issue by inklesspen** [syntax-tree/hast-util-to-parse5#5]
```js
var hastUtilToParse5 = require("hast-util-to-parse5")
var h = require("hastscript");

const el = h('input', {'minLength': 5});
const ast = hastUtilToParse5(el);
```

HAST permits the minLength attribute to be a number, but [parse5's AST](https://github.com/inikulin/parse5/blob/master/packages/parse5/docs/tree-adapter/default/attribute.md) requires that values be strings. Attempting to serialize the AST obtained from this snippet results in an exception.

**Comment by wooorm** [comment]
Hi Rose! Sounds about right! Are you able and interested to tackle this and work on a PR?

**Comment by inklesspen** [comment]
Unfortunately I'm not 100% sure how to fix it.

**Comment by wooorm** [comment]
Hmm, I can guide you, or take over if you want but I don’t have a lot of time so that could delay it a bit.

If I can guide you: could you provide me with more information on how you noticed this problem? What’s the background and why did you open an issue?

**Comment by inklesspen** [comment]
because I was using parse5 to parse html into HAST, I wanted to use parse5 to serialize as well, reasoning that parse5 would not produce html which it could not then parse.

I implemented a rehype serializer like this:

```js
import { serialize as parse5Serialize } from 'parse5';
import hastUtilToParse5 from 'hast-util-to-parse5';

export default function stringify(options) {
  // eslint-disable-next-line no-unused-vars
  const settings = { ...options, ...this.data('settings') };

  function compiler(tree) {
    const ast = hastUtilToParse5(tree);
    return parse5Serialize(ast);
  }

  this.Compiler = compiler;
}
```

but it ran into a problem round-tripping a `<font size="4">` tag. (Yes, I know nobody should actually use `<font>` anymore, but I needed to interoperate with older software that needs font sizes to be specified this way.) parse5 could parse it just fine into a value of `"4"`, but `hast-util-from-parse5` was converting that into `4` and `hast-util-to-parse5` did not convert it back.

I have worked around the issue with the following hack:

```js
import { serialize as parse5Serialize } from 'parse5';
import hastUtilToParse5 from 'hast-util-to-parse5';
import utilVisit from 'unist-util-visit';
import isElement from 'hast-util-is-element';
import reduce from 'immer';

function makeAttrValuesStrings(hast) {
  // due to https://github.com/syntax-tree/hast-util-to-parse5/issues/5
  // we must walk the tree and convert every attribute value to a string
  return reduce(hast, (draftHast) => {
    utilVisit(draftHast, node => isElement(node), (node) => {
      if (node.properties) {
        Object.keys(node.properties).forEach((propName) => {
          const value = node.properties[propName];
          if (value !== null && value !== undefined &&
            value !== false && !(value instanceof String)) {
            // eslint-disable-next-line no-param-reassign
            node.properties[propName] = value.toString();
          }
        });
      }
    });
  });
}

export default function stringify(options) {
  // eslint-disable-next-line no-unused-vars
  const settings = { ...options, ...this.data('settings') };

  function compiler(tree) {
    const hast = makeAttrValuesStrings(tree);
    const ast = hastUtilToParse5(hast);
    return parse5Serialize(ast);
  }

  this.Compiler = compiler;
}
```

I am worried my workaround will fail to properly handle some edge cases. If you can provide a better way of determining which attribute values to make strings, I can probably give you a PR.
